### ISSUE TITLE
output file contains only channels but no programms

### ISSUE THREAD

**Issue by jakubklos77** [frantisheq/rbxmltv#3]
Hello Frantisek
I would like to switch to your ruby based parser. 

It seems to work and download the cache properly (contains data with channel ids and program data) but the output xml file contains only channels and no data.

This is how I run it
./main.rb -d 3 -o ./test.xml -c ./cache

Am I doing something wrong?
Thank you very much
Jakub

**Comment by jakubklos77** [comment]
Ok, the issue is with the line:
        counter += Nokogiri::XML(File.read("#{cachedir}/#{channel.id}-#{date.strftime('%Y%m%d')}.xml")).css('p').count

If you comment this, it starts working. 
Should be fixed though

**Comment by frantisheq** [comment]
sice neskoro ale dik za info. upravil som to iba pre ceske a slovenske stanice aby sme zbytocne nebombardovali server poziadavkami niekolko hodin
